version: '3'

services:
  mediator:
    container_name: 'mediator'
    env_file:
      - .env
    restart: always
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: ./mediator/Dockerfile
      context: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_INTERNAL_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_SHOW_SQL=false
    ports:
      - "8080:8080"
    networks:
      - internal

  db:
    container_name: 'db'
    image: postgres:13.1-alpine
    env_file:
      - .env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 20s
      retries: 5
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - ../postgres/data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    name: internal