spring:
  application:
    name: tictactoe
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432}/${DATABASE_NAME:tictactoe}?currentSchema=${DATABASE_SCHEMA:public}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1608}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: public
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

config:
  sleep-duration: PT1S
  game-field-size: 19
